spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode : never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

logging:
  level:
    root: info


cloud:
  aws:
    s3:
      bucket: umc-5th
    region:
      static: ap-northeast-2
    stack:
      auto:false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_KEY}
